version: "3.8"

services:
  app:
    container_name: cassia-frontend
    image: cassia-frontend
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3001